name: stainsegmy-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - click=8.3.1
  - numpy=1.26.4
  - pandas=3.0.1
  - rich=14.3.3
  - tifffile=2023.8.12
  - imagecodecs=2023.1.23
  - captum=0.8.0
  - pip
  - pip:
      - pytorch_lightning==2.6.1
      #- torchvision

# pip install torch==2.1.1 torchvision==0.16.1 --index-url https://download.pytorch.org/whl/cu121
# pip install torch==2.1.1 torchvision==0.16.1 --index-url https://download.pytorch.org/whl/cu118